### PR TITLE
Remove .php in path when defining a route

### PR DESCRIPTION
**Pull request by vimkaf**
Remove .php in path when defining a route

### CODE REVIEW

**Comment by phprouter** [comment]
Nor sure if I would like to do this... somehow I like the fact that the developer explicitly writes the file extension. Suggestions?

**Comment by vimkaf** [comment]
Removing the .php makes it feel more like a path to a route and not just a regular include

**Comment by Orio-nn** [comment]
> Nor sure if I would like to do this... somehow I like the fact that the developer explicitly writes the file extension. Suggestions?

I don't know, I like it. Less written on the users side, better I say.

**Comment by phprouter** [comment]
Thank you for the comments. I have updated the router. Now the routes can contain ".php" or not.

**Pull request closed without merging**
